# Define a global platform for your project
platform :ios, '12.0'

# Specify the path to the Xcode project
project 'Runner.xcodeproj'

target 'Runner' do
  # Use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  # Firebase pods
  pod 'Firebase/Core', '~> 10.0'
  pod 'Firebase/Firestore', '~> 10.0'
  pod 'Firebase/Auth', '~> 10.0'
  pod 'Firebase/Storage', '~> 10.0'
  pod 'Firebase/AppCheck', '~> 10.0'
  pod 'Firebase/Analytics', '~> 10.0'

  # Add any other pods you need

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end

  # Ensure that all modules are correctly linked
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['DEFINES_MODULE'] = 'YES'
    end
  end
end
