# Define a global platform for your project
platform :ios, '13.0'

# Specify the path to the Xcode project
project 'Runner.xcworkspace'

target 'Runner' do
  # Use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing (if any)
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO' # Disable Bitcode
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64' # Exclude arm64 for simulator
    end
  end
end
